### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by zularizal** [amazing-username/Mear#37]
Hi @amazing-username , I'm a graphic designer. Your project looks interesting to me.

Can I contribute by making a logo for this project? It's free.

**Comment by amazing-username** [comment]
Hey @zularizal, most definitely! I'll update on how to contribute to this project so you can be a part of it.

**Comment by zularizal** [comment]
Hi @, this is the design logo for your project. This logo is inspired by a play button, note tone and shockwave. I have several color choices.
What do you think?
If there is something you want to change, let me know.
![bitmap](https://user-images.githubusercontent.com/38547278/54730136-c81eb780-4bb9-11e9-811c-2bf698f3ef10.png)

**Comment by amazing-username** [comment]
Hey @zulariza, man. I really like the logo. Particularly number 2 as well as the white logo against a black background. Could you provide a logo image with the same design as number 2 but change the primary color to purple (something like this color *#360485*) and have a similar gradient-like pattern where it is getting slightly bright?

Sorry for the late reply. I've been working on other projects that will support this project.

**Comment by zularizal** [comment]
Hi @amazing-username , Do you mean like this?

![bitmap](https://user-images.githubusercontent.com/38547278/54888623-3a044300-4ed1-11e9-9a56-db3662f547cd.png)

**Comment by amazing-username** [comment]
Hey @zularizal, I updated [CONTRIBUTING.md](https://github.com/amazing-username/Mear/blob/master/CONTRIBUTING.md) which has a section for Graphic Designers.

I really like that logo! One minor thing though, could you change the background to black? 

For the logos I'm looking for images to be in a PNG format and in the following dimensions:
* [72x72](https://github.com/amazing-username/Mear/tree/master/app/src/main/res/mipmap-hdpi)
* [48x48](https://github.com/amazing-username/Mear/tree/master/app/src/main/res/mipmap-mdpi)
* [96x96](https://github.com/amazing-username/Mear/tree/master/app/src/main/res/mipmap-xhdpi)
* [144x144](https://github.com/amazing-username/Mear/tree/master/app/src/main/res/mipmap-xxhdpi)
* [192x192](https://github.com/amazing-username/Mear/tree/master/app/src/main/res/mipmap-xxxhdpi)

I provided links on where to place these images for the various screens

**Comment by zularizal** [comment]
Hi, I have made a pull request for you.  #40 

And also I uploaded the logo to the drive. Check this link.
https://drive.google.com/open?id=1wASdLpsa55Bh1A9lA_a7WlXXxVwRrnyg

**Comment by amazing-username** [comment]
Hey @zularizal, just want to say that the logos you made are really appreciated and they look great too!

**Comment by zularizal** [comment]
Okay @amazing-username , if you have another open source project. Don't be shy to contact me, I've never taken a fee and it's completely free.

**Comment by amazing-username** [comment]
@zularizal, Most definitely! I have some other open source projects that will integrate with this one but I'm still planning for it
